"""LLM prediction test run for longitudinal child crime Books of Life.

Uses the person-specific-cutoff books generated by
`create_child_bol_longitudinal_cutoff.py`.
"""
from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

import pandas as pd


REPO = Path(__file__).resolve().parent
OUT_DIR = REPO / "data/processed_child_crime_longitudinal"
BOOKS_JSON = OUT_DIR / "books_child_crime_longitudinal_cutoff.json"
TARGETS_CSV = OUT_DIR / "child_crime_longitudinal_targets.csv"
SAMPLE_IDS_CSV = OUT_DIR / "child_crime_longitudinal_sample_ids_120.csv"
SAMPLE_BOOKS_JSON = OUT_DIR / "books_child_crime_longitudinal_sample_120.json"
PREDICTIONS_CSV = OUT_DIR / "child_crime_longitudinal_llm_predictions_120.csv"

TARGET = "later_justice_contact_repeated_years"
DEFAULT_MODEL = "gpt-5.4-nano"
SAMPLE_N = 120


def load_env(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def parse_jsonish(text: str) -> dict:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, flags=re.DOTALL)
        if not match:
            raise
        return json.loads(match.group(0))


def make_or_load_sample(books: dict, targets: pd.DataFrame) -> pd.DataFrame:
    if SAMPLE_IDS_CSV.exists():
        sample = pd.read_csv(SAMPLE_IDS_CSV)
        return sample

    eligible = targets[targets[TARGET].notna() & targets["C0000100"].astype(int).astype(str).isin(books)].copy()
    pos = eligible[eligible[TARGET] == 1].sample(n=SAMPLE_N // 2, random_state=2026)
    neg = eligible[eligible[TARGET] == 0].sample(n=SAMPLE_N - len(pos), random_state=2027)
    sample = pd.concat([pos, neg], ignore_index=True).sample(frac=1, random_state=2028)
    sample.to_csv(SAMPLE_IDS_CSV, index=False)
    return sample


def make_prompt(book_text: str) -> str:
    return f"""Read the Book of Life below and predict whether this person will have repeated later justice-system contact.

The target equals 1 if the person has positive justice-contact reports in at least two different later survey years from 2000-2020. Justice contact is based on probation or being sentenced to corrections/jail/reform. The Book of Life has already been cut off before the target point: for positive cases, information after the repeated-contact event year is omitted; for negative cases, information after the last observed target year is omitted.

Return only valid JSON with exactly these keys:
{{"prediction": 0 or 1, "probability": number between 0 and 1, "reason": "one short sentence"}}

Use `probability` as your estimated probability that the target equals 1.

Book of Life:
{book_text}
"""


def predict_one(client, model: str, book_text: str) -> dict:
    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "system",
                "content": (
                    "You are a careful research assistant making binary risk predictions from "
                    "structured life-history text. Return compact JSON only."
                ),
            },
            {"role": "user", "content": make_prompt(book_text)},
        ],
        max_output_tokens=180,
    )
    parsed = parse_jsonish(response.output_text)
    return {
        "prediction": int(parsed["prediction"]),
        "probability": float(parsed["probability"]),
        "reason": str(parsed.get("reason", "")),
        "raw_response": response.output_text,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    load_env(REPO / ".env")
    model = os.environ.get("OPENAI_MODEL", DEFAULT_MODEL)

    books = json.loads(BOOKS_JSON.read_text())
    targets = pd.read_csv(TARGETS_CSV)
    sample = make_or_load_sample(books, targets)
    sample_ids = [str(int(x)) for x in sample["C0000100"]]
    sample_books = {cid: books[cid] for cid in sample_ids if cid in books}
    SAMPLE_BOOKS_JSON.write_text(json.dumps(sample_books, indent=2, sort_keys=True))

    existing = pd.DataFrame()
    if PREDICTIONS_CSV.exists() and not args.overwrite:
        existing = pd.read_csv(PREDICTIONS_CSV)
        done = set(existing["C0000100"].astype(int).astype(str))
        sample_books = {cid: payload for cid, payload in sample_books.items() if cid not in done}

    print(f"Sample size: {len(sample_ids)}")
    print(f"Books to predict: {len(sample_books)}")
    print(f"Model: {model}")

    if args.dry_run:
        first_id, first_book = next(iter(sample_books.items()))
        print("\n=== Dry-run prompt excerpt ===")
        print(make_prompt(first_book["text"])[:1800])
        return

    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise SystemExit("OPENAI_API_KEY is missing. Add it to .env.")

    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    rows = []
    truth = sample[["C0000100", TARGET, "cutoff_year_for_repeated_target"]].copy()
    truth["C0000100"] = truth["C0000100"].astype(int)

    for child_id, payload in sample_books.items():
        pred = predict_one(client, model, payload["text"])
        rows.append({"C0000100": int(child_id), "model": model, "target": TARGET, **pred})
        print(f"Predicted {child_id}: {pred['prediction']} p={pred['probability']:.3f}")

    new_preds = pd.DataFrame(rows)
    if len(new_preds):
        new_preds = new_preds.merge(truth, on="C0000100", how="left")
        new_preds.rename(columns={TARGET: "y_true", "cutoff_year_for_repeated_target": "cutoff_year"}, inplace=True)
        new_preds["correct"] = new_preds["prediction"] == new_preds["y_true"]

    if len(existing) and not args.overwrite:
        preds = pd.concat([existing, new_preds], ignore_index=True)
        preds = preds.drop_duplicates(["C0000100", "target"], keep="last")
    else:
        preds = new_preds
    preds.to_csv(PREDICTIONS_CSV, index=False)

    print(f"\nWrote {len(preds)} predictions to {PREDICTIONS_CSV.relative_to(REPO)}")
    if "y_true" in preds and preds["y_true"].notna().any():
        print(f"Accuracy using model prediction column: {preds['correct'].mean():.3f}")


if __name__ == "__main__":
    main()
